version: '3.8'

services:
  discoveryserver:
    build:
      context: .
      dockerfile: discoverserver/dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservice-networks
networks:
  microservices-networks:
    driver: bridge