version: "3.8"

services:
    discoverserver:
        build:
            context: .
            dockerfile: discoverserver/Dockerfile
        ports:
            - "8761:8761"
        networks:
            - microservices-network

networks:
    microservices-network:
        driver: bridge
